"""Initial schema

Revision ID: 9090788874b5
Revises: 
Create Date: 2026-05-23 16:36:42.219560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9090788874b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexers',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indexers'))
    )
    op.create_table('preference_definitions',
    sa.Column('preference_id', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preference_definitions'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('token', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('torrent_seed', sa.Integer(), nullable=True),
    sa.Column('only_best_torrent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_token'), ['token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('preference_definition_attributes',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('attribute_id', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['preference_definitions.id'], name=op.f('fk_preference_definition_attributes_definition_id_preference_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preference_definition_attributes'))
    )
    op.create_table('system_preferences',
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['preference_definitions.id'], name=op.f('fk_system_preferences_definition_id_preference_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('definition_id', name=op.f('pk_system_preferences'))
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['preference_definitions.id'], name=op.f('fk_user_preferences_definition_id_preference_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_table('system_preferences')
    op.drop_table('preference_definition_attributes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_token'))

    op.drop_table('users')
    op.drop_table('preference_definitions')
    op.drop_table('indexers')
    # ### end Alembic commands ###
