name: PR Check

on:
  pull_request:
    branches: [main]
    paths:
      - "client/**"
      - "server/**"
      - ".github/workflows/**"

jobs:
  server:
    name: Server
    uses: ./.github/workflows/reusable-server-test-build.yaml
    with:
      working-directory: ./server
    secrets: inherit

  client:
    name: Client
    uses: ./.github/workflows/reusable-client-test-build.yaml
    with:
      working-directory: ./client
    secrets: inherit
